server:
  port: 8081
  tomcat:
    # 默认编码
    uri-encoding: UTF-8
    max-threads: 0
  session-timeout: 10
spring:
  application:
    name: Spring-Boot-Auth-Code
  mvc:
    view:
      # 默认前缀
      prefix: /
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  thymeleaf:
    prefix: classpath:/templates
    cache: false
